// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ38bI7-JscMRJ81GsCfMNbNcsV73VZCs',
    appId: '1:392694761362:web:dbe9a87a4850eaa633e34b',
    messagingSenderId: '392694761362',
    projectId: 'delivery-app-a835a',
    authDomain: 'delivery-app-a835a.firebaseapp.com',
    storageBucket: 'delivery-app-a835a.appspot.com',
    measurementId: 'G-E164LK3TT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-nutNIpr_9csm2354vSpgcSFlwFxTG8s',
    appId: '1:392694761362:android:cb1b5e7350b556cc33e34b',
    messagingSenderId: '392694761362',
    projectId: 'delivery-app-a835a',
    storageBucket: 'delivery-app-a835a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOrfwSXO_9WZ2vZOhq5pbxoLn9rkTnlE8',
    appId: '1:392694761362:ios:dd9b80249bacb99033e34b',
    messagingSenderId: '392694761362',
    projectId: 'delivery-app-a835a',
    storageBucket: 'delivery-app-a835a.appspot.com',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOrfwSXO_9WZ2vZOhq5pbxoLn9rkTnlE8',
    appId: '1:392694761362:ios:dd9b80249bacb99033e34b',
    messagingSenderId: '392694761362',
    projectId: 'delivery-app-a835a',
    storageBucket: 'delivery-app-a835a.appspot.com',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ38bI7-JscMRJ81GsCfMNbNcsV73VZCs',
    appId: '1:392694761362:web:1d0407479bf3628033e34b',
    messagingSenderId: '392694761362',
    projectId: 'delivery-app-a835a',
    authDomain: 'delivery-app-a835a.firebaseapp.com',
    storageBucket: 'delivery-app-a835a.appspot.com',
    measurementId: 'G-3FSE2LGPBP',
  );
}
