import 'package:hive/hive.dart';
part 'menu_model.g.dart'; // This file will be generated by Hive

@HiveType(typeId: 0)
class MenuModel extends HiveObject{
  @HiveField(0)
  int? id;
  @HiveField(1)
  String? title;
  @HiveField(2)
  String? restaurantChain;
  @HiveField(3)
  String? image;
  @HiveField(4)
  String? imageType;
 

  MenuModel({
    this.id,
    this.title,
    this.restaurantChain,
    this.image,
    this.imageType,
  
  });

  factory MenuModel.fromJson(Map<String, dynamic> json) => MenuModel(
        id: json['id'] as int?,
        title: json['title'] as String?,
        restaurantChain: json['restaurantChain'] as String?,
        image: json['image'] as String?,
        imageType: json['imageType'] as String?,
    
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'title': title,
        'restaurantChain': restaurantChain,
        'image': image,
        'imageType': imageType,
    
      };
}
